reference_reader/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('reference_reading.urls')),
]

reference_reading/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'reference_reading'
urlpatterns = [
    #home page
    path('',views.index, name='index'),
    #list of files
    path('files/', views.files, name='files'),
    #references of files
    path('files/<int:file_id>/', views.cite, name='cite'),
    #add a new file
    path('new_file', views.new_file, name='new_file'),
    #download current file
    path('download/<int:file_id>', views.download, name='downloading'),
    #deleting current file
    path('delete/<int:file_id>', views.delete_file, name='delete'),
    #decors
    path('decor/<file_name>', views.decor, name='decor'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, include
from . import views


app_name = "users"
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),

]

reference_reading/models.py
from django.db import models
from django.contrib.auth.models import User

# list of uploaded file names
class File_Name(models.Model):
    title = models.CharField(max_length=200)
    name = models.FileField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

reference_reading/forms.py
from django import forms
from .models import File_Name

#for uploading doc file
class UploadFileForm(forms.ModelForm):
    class Meta:
        model = File_Name
        fields = ['title', 'name']
        labels = {'title': 'Title', 'name': ''}

reference_reading/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
import docx
from django.contrib import messages
import googlesearch
import os
from django.conf import settings
from django.http import HttpResponse, Http404
from django import template

# the home page view function
# ties the neccessary html file with the view model
def index (request):
    return render(request, 'reference_reading/index.html')
# the page with the list of files uploaded
# redirects to login page if no one is logged in with @login_required
@login_required
def files(request):
    file = File_Name.objects.filter(owner=request.user).order_by('date_added')
    context = {"file": file}
    return render(request, 'reference_reading/files.html', context)
# function that searches for the right info to display for references
# Finds the author and title of the source
# could use some improvement
def handle_uploaded_file(list, rtn_list):
    if list != []: # empty list?
        for para in list[:-1]: # for each paragraph in the list received from read_dcx()
            if '“' in para: # removes the extra " present
                para = para.replace('“','')
            part = para.split('.') # splits the paragraphs by sentence using the period as stamps
            part[0] = part[0] + ':' # adds colon next to the author name(s) for display when rendered
            if len(para[0]) <= 21: # if the first element is over 21 characters (to check if its a name), it won't recognize
                                   # the citation as a proper mla format and skips it
                rtn_list.append(' '.join(part[0:2])) # specifically joins only the author and title elements
            else:
                pass
        return rtn_list
    else:
        return rtn_list
# uses the docx API in order to read and organize a docx file by paragraph
def read_dcx(file):
    fullText = []
    for para in file.paragraphs: # takes each paragraph and inserts them into a list
        fullText.append(para.text)
    full = ''.join(fullText)
    return fullText
#
def google_search_reference(list, rtn_list): # unused because the execution time is too slow
    if list != []:
        ele = googlesearch.search(list[0], tld='com', lang='en', num=10, start=0, stop=None, pause=2.0)
        rtn_list.append(ele[0])
        google_search_reference(list[1:], rtn_list)
    elif list == []:
        pass
    return rtn_list

# Function to download file being currently viewed
def download(request, file_id):
    file = get_object_or_404(File_Name, id=file_id) # grabs current file
    file_path = os.path.join(settings.MEDIA_ROOT, file.name.path)
    if os.path.exists(file_path) and request.method == 'POST': # if the file path exists and POST is present
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type="application/vnd.ms-excel")
            response['Content-Disposition'] = 'inline; filename=' + os.path.basename(file_path)
            return response
    raise Http404
    # this would technically replace context rendered when opening the page with this one
    # however because the page doesn't need to update or alter after already being rendered
    # this isn't a problem and would respectfully reset after reopening this page
    context = {'files': file}
    return render(request, 'reference_reading/cite.html', context)

def delete_file(request, file_id):
    file = get_object_or_404(File_Name, id=file_id)
    if request.method == 'POST':
        file.delete()
        os.remove(file.name.path)
        return redirect('reference_reading:files')
    context = {"files": file}
    return render(request, 'reference_reading:cite.html', context)

# View function for the page full fo the file's references
@login_required
def cite(request, file_id):
    file = get_object_or_404(File_Name, id=file_id)
    if file.owner != request.user: #security
        raise Http404
    # process docx file
    doc = docx.Document(file.name.path)
    full = read_dcx(doc)
    if "Work Cited" in full:
        full = full[((full.index('Work Cited ')) + 1):]
    elif "Work Cited " in full:
        full = full[((full.index('Work Cited')) + 1):]
    elif "Cited" in full:
        full = full[((full.index('Cited'))+1):]
    elif 'Citations' in full:
        full = full[(full.index('Citations'))+1:]
    elif 'Citations ' in full:
        full = full[(full.index('Citations '))+1:]
    elif "Cited " in full:
        full = full[((full.index('Cited ')) + 1):]
    else:
        full = []
    l1 = (handle_uploaded_file(full, []))
    # transfer data to html
    context = {'files': file, 'ref': l1}
    return render(request, 'reference_reading/cite.html', context)
# View function for uploading a new file
# Uploads file along with adding a name to the entry
@login_required
def new_file(request):
    if request.method != 'POST':
        form = UploadFileForm()
    else:
        form = UploadFileForm(request.POST, request.FILES)
        for filename, file in request.FILES.items():
            val = request.FILES[filename].name
        if form.is_valid() and '.docx' in val:
            new_file = form.save(commit=False)
            new_file.owner = request.user
            new_file.save()
            return redirect('reference_reading:files')
        else:
            form = UploadFileForm()
            messages.success(request, 'You may only upload a ".DOCX" file')
    context = {'form': form}
    return render(request, 'reference_reading/new_file.html', context)

def decor(file_name):
    file_name = os.path.abspath('bg_jumbo.jpg')
    return file_name

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('reference_reading:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

reference_reading/templates/reference_reading/base.html
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial scale=1, shrink-to-fit=no">
    <title>Reference Reader</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<style>
.option_variant::after{content:'';display:block;width:0px;height:2px;background:#fec400;transition: 0.2s;}
.option_variant:hover::after{width:95%;}
.option_variant {
    transition:0.2s;
.nav-item.active, .nav-item:active{color:#212529;}
.nav-item:focus, .nav-item:hover{background:#fec400;}
}
</style>
<body>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <nav class="navbar navbar-expand-md navbar-light bg-dark mb-4 border">

        <a style='color:white' class="navbar-brand" href="{% url 'reference_reading:index' %}">Reference Dojo</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle-navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item option_variant">
                    <a style='color:white' class="nav-link" href="{% url 'reference_reading:files'%}">
                        <i class="fas fa-file" style="padding-right: 2px;"></i> Files</a>
                </li>
                <li class="nav-item option_variant">
                    <a style="color:white" class="nav-link" href="{% url 'reference_reading:new_file'%}">
                        <i style="padding-right: 2px;" class="fas fa-plus"></i>Add File</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li style="padding-right: 5px;">
                        <span style='color:white'class="navbar-text">You are logged in as {{user.username}}</span>
                    </li>
                    <li class="nav-item">
                        <a style='color:white' class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a style='color:white' class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a style='color:white' class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>


</body>
</html>

reference_reading/templates/reference_reading/cite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Citations</title>
</head>
<style>
.floated {
    float:left;
    margin-right:5px;
    margin-bottom:5px;
}
</style>
{% extends 'reference_reading/base.html' %}
{%block page_header%}
    <h1>{{files}}</h1>
    <p>File: {{files.name.name}}</p>

{%endblock page_header %}

{% block content %}
    {% for references in ref %}
    <li><p>{{references}}</p></li>
    {% empty %}
    <p>No References Found</p>
    {% endfor %}
    <hr>
    <form class="floated" action="{% url 'reference_reading:downloading' files.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Download file">
    </form>

    <form style="float: right;" class="floated" action="{% url 'reference_reading:delete' files.id %}" method="post">
        {% csrf_token %}
        <input style="float: right" type="submit" value="Delete file">
    </form>
    </hr>

{% endblock content %}
</body>
</html>

reference_reading/templates/reference_reading/files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Files</title>
</head>
<style>
.file_entry:hover {
    color: #707070;
}
.file_entry {
    color: black;
}
</style>
<body>
{%extends "reference_reading/base.html"%}
{%block page_header%}
    <h1>Files
        <a style="text-decoration: none; float: right;" href="{% url 'reference_reading:new_file' %}">
            <i style="padding: 10px; color: green;" class="fas fa-plus"></i>Add a new file
        </a>
    </h1>
{%endblock page_header %}
{% block content %}
    {% for files in file %}
        <h3 style="border-bottom:1px solid rgba(0, 0, 0, .15); background-clip: padding-box;">
            <a style="text-decoration: none;" class="file_entry" href="{% url 'reference_reading:cite' files.id %}">{{files}}</a>
            <p style="font-size:12px;">{{files.date_added}}</p>
        </h3>
    {% empty %}
        <li><h3>No files have been added yet</h3></li>
    {% endfor %}
{% endblock content %}

</body>
</html>

reference_reading/templates/reference_reading/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reference Dojo</title>
</head>
<style>
.jumbotron {
    background-image: url('http://9a2e1a2047765d2a004e-e6d2db425d8d4f2619e5cee56a48bcef.r55.cf2.rackcdn.com/clouds.png');
    background-size: cover;
}
</style>
<body>
{% extends "reference_reading/base.html" %}
{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">Track your MLA references</h1>
        <p class="lead">Upload a Word Document to obtain citations!</p>
        {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-primary" href="{% url 'reference_reading:files' %}"
           role="button">Go to files &raquo;</a>
        {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
           role="button">Register &raquo;</a>
        {% endif %}

    </div>
{% endblock content %}

</body>
</html>

reference_reading/templates/reference_reading/new_file.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>File Upload</title>
</head>
<body>
{% extends "reference_reading/base.html" %}
{% block content %}
    <p>Add a new file</p>

    <form action="{% url 'reference_reading:new_file' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %} <!---malware protection--->
        {{ form.as_p }}
        <button name="submit" >Add File</button>
    </form>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {%endfor%}
        </ul>
    {% endif %}

{% endblock content %}
</body>
</html>